server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/j2eety/microservicecloud-config.git #GitHub上面的git仓库名字
          username: j2eety
          password: 199212ty